name: CD - STG

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  setup:
    uses: ./.github/workflows/setup.yml
    with:
      ENV: production
    secrets: inherit

  build:
    needs: [setup]
    uses: ./.github/workflows/build.yml
    with:
      PATH: dist
      ENV: production
      COMMAND: build:prod
    secrets: inherit